"""init

Revision ID: 35306fafd39f
Revises: 
Create Date: 2022-08-11 17:17:34.613366

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "35306fafd39f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("password", sa.String(length=100), nullable=True),
        sa.Column("api_key", sa.String(length=100), nullable=True),
        sa.Column("follower_count", sa.Integer(), nullable=True),
        sa.Column(
            "follower", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "following", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("soft_delete", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_authors_api_key"), "authors", ["api_key"], unique=True
    )
    op.create_index(op.f("ix_authors_name"), "authors", ["name"], unique=True)
    op.create_index(
        op.f("ix_authors_password"), "authors", ["password"], unique=False
    )
    op.create_table(
        "tweets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column(
            "likes", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("soft_delete", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.PrimaryKeyConstraint("id", "author_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tweets")
    op.drop_index(op.f("ix_authors_password"), table_name="authors")
    op.drop_index(op.f("ix_authors_name"), table_name="authors")
    op.drop_index(op.f("ix_authors_api_key"), table_name="authors")
    op.drop_table("authors")
    # ### end Alembic commands ###
