"""init

Revision ID: 473b289ca8c2
Revises: 
Create Date: 2022-09-01 22:22:46.378769

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "473b289ca8c2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("password", sa.String(length=100), nullable=True),
        sa.Column("api_key", sa.String(length=100), nullable=True),
        sa.Column("follower_count", sa.Integer(), nullable=True),
        sa.Column("followers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("following", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("soft_delete", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_authors_api_key"), "authors", ["api_key"], unique=True)
    op.create_index(op.f("ix_authors_name"), "authors", ["name"], unique=True)
    op.create_index(op.f("ix_authors_password"), "authors", ["password"], unique=False)
    op.create_table(
        "medias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("link", sa.String(length=100), nullable=True),
        sa.Column("hash", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_medias_hash"), "medias", ["hash"], unique=True)
    op.create_table(
        "tweets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.Column("likes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("soft_delete", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tweets")
    op.drop_index(op.f("ix_medias_hash"), table_name="medias")
    op.drop_table("medias")
    op.drop_index(op.f("ix_authors_password"), table_name="authors")
    op.drop_index(op.f("ix_authors_name"), table_name="authors")
    op.drop_index(op.f("ix_authors_api_key"), table_name="authors")
    op.drop_table("authors")
    # ### end Alembic commands ###
