"""сделал пароль

Revision ID: 5aa4078f6ad1
Revises: 5cc408b1cdc9
Create Date: 2022-08-08 20:14:53.267208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa4078f6ad1'
down_revision = '5cc408b1cdc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('password', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_authors_password'), 'authors', ['password'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authors_password'), table_name='authors')
    op.drop_column('authors', 'password')
    # ### end Alembic commands ###
