"""add index to user name

Revision ID: 5cc408b1cdc9
Revises: ce904ac2994b
Create Date: 2022-08-07 21:52:29.007308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc408b1cdc9'
down_revision = 'ce904ac2994b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    # ### end Alembic commands ###
