"""patch author model

Revision ID: 7c299968c60a
Revises: f823c79513ce
Create Date: 2022-08-07 00:04:54.857383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c299968c60a'
down_revision = 'f823c79513ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('api_key', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'api_key')
    # ### end Alembic commands ###
