"""add index to apikey

Revision ID: ce904ac2994b
Revises: 7c299968c60a
Create Date: 2022-08-07 00:08:17.121908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce904ac2994b'
down_revision = '7c299968c60a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_authors_api_key'), 'authors', ['api_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authors_api_key'), table_name='authors')
    # ### end Alembic commands ###
