"""init

Revision ID: f823c79513ce
Revises: 
Create Date: 2022-08-05 00:19:21.669602

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f823c79513ce"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("follower_count", sa.Integer(), nullable=True),
        sa.Column(
            "follower", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "following", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("soft_delete", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tweets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column(
            "likes", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("soft_delete", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.PrimaryKeyConstraint("id", "author_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tweets")
    op.drop_table("authors")
    # ### end Alembic commands ###
