ARG ELK_VERSION

# https://www.docker.elastic.co/
#FROM elasticsearch:${ELK_VERSION}
FROM elasticsearch:8.4.3

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
